# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD$

PORTNAME=	libXcomposite
PORTVERSION=	0.4.4
PORTREVISION=	3
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Composite extension library

XORG_CAT=	lib
USE_XORG=	x11 xfixes xext xorgproto

.include <bsd.port.mk>
